### PR TITLE
Fixed test for freetorrents plugin.

### PR DESCRIPTION
**Pull request by rk4n**

### CODE REVIEW

**Comment by werwolfby** [comment]
It looks better than my own. Thanks a lot!

**Comment by rk4n** [comment]
travis haven't even got a chance to start :grinning: 
```
The command "eval git fetch origin +refs/pull/158/merge:" failed. Retrying, 2 of 3.
```

**Comment by werwolfby** [comment]
```
No module named 'urlparse'
```
For python 3

Could please use ```six``` for fix it?

I was too fast 😀

**Comment by rk4n** [comment]
@werwolfby sure

**Pull request merged**
