### PR TITLE
Update lostfilm.py

### PR DESCRIPTION
**Pull request by Akior**
Сменилась структура у lostfilm

### CODE REVIEW

**Comment by melnikdima90** [comment]
Please update the checking module for lostfilm.tv.

**Comment by werwolfby** [comment]
Thank you, will merge soon

**Comment by werwolfby** [comment]
Yep, requires updates on tests, will do

**Comment by werwolfby** [comment]
Close by cherry pick the commint: 70efff5649f3f63ad40b86b3af4de6f6bedb417c

**Pull request closed without merging**
