### PR TITLE
Implemented #137 - Manual execute single topic/tracker shouldn't reset timeout

### PR DESCRIPTION
**Pull request by rk4n**
#137 Implemented timer via separate thread pushing messages to worker's priority queue.
Added two types of message:
- stop_message that has the highest priority
- run_message that can be parametrized with list of ids 

Added unit tests just to `engine.py`.
Not sure if api tests are needed here, will add them if needed.

### CODE REVIEW

**Comment by werwolfby** [comment]
@rk4n thank you for this PR, will review it in nearest days

**Comment by rk4n** [comment]
@werwolfby Cool !
All builds are failing, which is not good.
- Travis fails on `1.0.0-rc.0 is not valid SemVer string`.
- appveyor has some environment related issues 
- codacy seem to report more and more each time

**Comment by werwolfby** [comment]
@rk4n I saw issues on travis, i think it will be fixed in nearest days as well :)
appveyor makes me angry for too long, don't how to fix it yet,
and codacy was added only month ago or so, so we didn't make any changes according to it

I'm worrying only about code coverage.

**Comment by werwolfby** [comment]
@rk4n thanks a lot for this changes, everything looks great!

Closed by manual rebase and minor fixes, you changes was applied.

**Comment by rk4n** [comment]
@werwolfby thanks. 

Just tested manually on my device, it doesn't seem to work properly. Gonna check it more accurately and create another PR if needed.

**Comment by werwolfby** [comment]
It's a bad news :(

**Comment by rk4n** [comment]
@werwolfby found the issue, will submit PR soon.

**Pull request closed without merging**
