### PR TITLE
Fix #146 HTTPS links don't work when adding new torrent

### LINKED ISSUE #146: HTTPS links don't work when adding new torrent
monitorrent 2016-10-18 10-10-23

### PR DESCRIPTION
**Pull request by XBeg9**

### CODE REVIEW

**Comment by XBeg9** [comment]
Issue #147

**Comment by werwolfby** [comment]
Could you please add test for this?
Example can be found here, and you can add test in that class: https://github.com/werwolfby/monitorrent/blob/develop/tests/plugins/trackers/tests_lostfilm/test_lostfilmtracker.py#L75-L79

Just add one test with **https** example, and don't forget to push generated cassette

**Comment by werwolfby** [comment]
And could you please update commit message to:
```
fix(plugins/lostfilm): fix #146 https links don't work when adding new torrent
```

**Comment by XBeg9** [comment]
I have a bit different dev stack, could you please help me with this `push generated cassette` ? As I understand, it's here.. https://github.com/kevin1024/vcrpy but how to generate it? Don't to waste time digging into documentation. Thanks @werwolfby

**Comment by werwolfby** [comment]
Just run this test
You can do it by run ```run_test.cmd``` on windows

**Comment by werwolfby** [comment]
Update: 
```coverage run -m unittest discover -s tests```
On all platforms

**Comment by XBeg9** [comment]
I don't know why AppVeyor is failing, any reasons? @werwolfby cassette has been added.

**Comment by werwolfby** [comment]
thank you @XBeg9 looks good. 
I'll wait for checks and will merge the changes.

**Comment by werwolfby** [comment]
@XBeg9  AppVeyor on fault state for last two month :(
We are working on fixes, but now without any luck, so don't worry.

**Pull request merged**
